### ISSUE TITLE
(subscript) logical subscript too long

### ISSUE THREAD

**Issue by renzy93** [jcao89757/TESSA#11]
Hi Ze，

     Different lengths of CDR3 sequence can be solved by Tessa, a wonderful tool.  I have an Error when I used my data running TCR network construction. The error is as followd:

Initialization
[1] 123
Error in t[, !duplicated(cdr3), drop = F] : 
  (subscript) logical subscript too long
Calls: Tessa -> initialize
Execution halted

embeding.csv have accomplished, but I cannot find out where is the error from. Could you give me some advice? I can run to completion the example, but the version is not completely the same as you. I dont know whether this mistake is caused by version.

Thanks a lot.
Ren

**Comment by laurentbartolo** [comment]
I have the same problem did you find a solution ?

**Comment by renzy93** [comment]
Maybe the contig_id of TCR and RNA-Seq is not the same.
















At 2022-01-14 00:46:37, "laurentbartolo" ***@***.***> wrote:

I have the same problem did you find a solution ?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
