### ISSUE TITLE
How to reconstructed 'Athley' matrices

### ISSUE THREAD

**Issue by renzy93** [jcao89757/TESSA#12]
Hi Ze，

       The code can change the CDR3 sequences to a 30-d numerical vector. I want to know how to find each or some numerical vector corresponding amino acid sequence like Extended Data Fig.1 a decoder.

Thanks a lot
Ren

**Comment by jcao89757** [comment]
Hi Ren，

Thanks for your interest in our tool! 

Would you please follow the example command in the last section of the github tutorial, _Note 3: Potential applications of Tessa on TCR data from other species_? That additional script could generate the reconstructed matrices similar to the ones we used in Ext. fig. 1.

I saw that you opened and revoked an issue a few weeks ago. Hope you have successfully solved that problem too. Please let me know if you have any other questions. Thanks!

Best regards, Ze

**Comment by renzy93** [comment]
Thank you very much for your advise. I am still trying to solve this problem. I am not very familiar with python. If there are problem that cannot be solved, i may bother you again.Thanks again Ren发自我的iPhone------------------ Original ------------------From: Ze Zhang  ***@***.***>Date: Sun,May 30,2021 4:34 AMTo: jcao89757/TESSA ***@***.***>Cc: renzy93 ***@***.***>, Author ***@***.***>Subject: Re: [jcao89757/TESSA] How to reconstructed 'Athley' matrices (#12)
Closed #12.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/jcao89757/TESSA/issues/12#event-4816416894",
"url": "https://github.com/jcao89757/TESSA/issues/12#event-4816416894",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jcao89757** [comment]
You are welcome! Please feel free to let me know your problems any time.

Best regards, Ze
