### ISSUE TITLE
ggplot2 is not loaded in plot_tessaClsuters function

### ISSUE THREAD

**Issue by zhangzlab** [jcao89757/TESSA#2]
Dear all,

I tried the Tessa tool and found in the post-analysis step, library ggplot2 is missed in function plot_tessaClsuters. This gives an error for R plotting. What's more, the error message 'ERROR: please input valid TCRs/embedding.' is confusing.

Best!

**Comment by jcao89757** [comment]
Hi, 
Thanks a lot for letting me know! I have been able to replicate the bugs you showed above, and the causes of the bugs have been detected. Sorry for causing your trouble! Please allow me a few days to fix the bugs, and I will reach you back early next week. 

Thanks again for your report!

Best regards, Ze

**Comment by jcao89757** [comment]
Hi,

Thanks for your patience!

All bugs have been fixed. Please try the tessa tool again with the latest 1.2.0 version scripts, and please be sure to have the updated dependencies installed. The plot_Tessa_Cluster function requires the R package 'igraph', which depends on ggplot2. If errors about ggplot2 appear then reinstall the igraph package may solve the problem.

Please let me know if you still have questions using tessa. Thanks again for your report!

Best regards, Ze
