### ISSUE TITLE
MCMC iterations number

### ISSUE THREAD

**Issue by BioLaoXu** [jcao89757/TESSA#3]
Hi, Dear TESSA developers,it is a good idea for clusering single cell by joint TCR  and RNA profile,,but Tessa takes too long to run，My guess is that this is caused by 1000 iterations of MCMC，So I would like to ask how the number of iterations affects the final result. Can I customize it?How much do you recommend?Thank you and I am looking forward to your reply.

**Comment by jcao89757** [comment]
Hi,

Thanks a lot for your interest in our tool!

Yes, you can definitely customize the max iteration rounds! Please edit line 51, the value of the parameter 'max_iter' in https://github.com/jcao89757/TESSA/blob/1.2.0/Tessa/real_data.R to your expected iteration rounds. 

It's really hard to estimate an optimal iteration round number under a wide variaty of conditions. I would suggest trying a small number of iteration loops, ane looking into the std_output 'b acceptance rate'. If the rate drops to ~0 for a few loops, then the algorithm is sure to converge, and you will be confident to stop the algorithm and analyze the clustering result. Please also refer to section 3.2: diagnosis for convergence in the supplementary note 1 of our paper https://www.nature.com/articles/s41592-020-01020-3 for more details.

Let me know if you have any further questions! Thanks again and wish you all the best!

Best regards, Ze

**Comment by BioLaoXu** [comment]
ok，I know how to set it，thanks a lot@jcao89757
