### ISSUE TITLE
Documentation for Rdata output

### ISSUE THREAD

**Issue by gouinK** [jcao89757/TESSA#4]
Greetings, brilliant tool and really excited to implement this. I was wondering if there was any documentation on the Rdata output? Specifically, I am assuming that the tessa_results$dt contains the TCR distances for each network, but I am unclear on the structure of it. 

For example, I would like to calculate the unexplained variance for some of my networks, which I think I can derive from this Rdata output, but I am just not sure how to get there without any explanation of the output structure. 

Thanks so much for your time!

**Comment by jcao89757** [comment]
Hi Kenny,

Great question!

Basically we have b, dt and de that may be helpful as input datasets of your downstream analysis. Once you load the tessa_final.RData result class, you will find 12 elements. (1) tessa_results$b is the estimated b values for a specific dataset. The b vector is a scale vactor for dts and please find more details in our paper. (2)  tessa_results$meta and meta_dedup represent the clustering of cells/clonotypes. (3) master_dist_e, a, and sigma: mediate parameters which may not be that informative. (4) at: linear slopes for all the clusters, named as the  CDR3 sequences of the center TCR clone. (5) dt and de: list of lists. Each of the list represent one cluster, as the name of the list represent the CDR3 sequence of the center TCR clone. The values in each list represent the distances from peripheral clones to the central clone (named as the pertipheral clone CDR3 sequences. (5) Phi and K: Clone populations of clusters and the total number of clusters.

Please find my code below to calculate the unexplained variances.

##########Code begins##################
load(# your tessa_results#)
dt=tessa_results$dt
de=tessa_results$de
ak=tessa_results$ak
for(k in 1:length(dt)){
      r2=c(r2,sum((de[[k]]-ak[k]*dt[[k]])^2)/sum((de[[k]]-mean(de[[k]]))^2))
    }
names(r2)=names(de)
##########End of my code################

Then r2 vector contains the unexplained variances for your networks.

Thanks a lot for your interest in our tool! Please let me know if you have any questions or concerns. I'll be glad to assist you and share my experience.

Best regards, Ze

**Comment by gouinK** [comment]
Hi Ze, 

Thanks so much for your thorough and quick response, this is extremely helpful!
My first full run of this on ~100k T-cells is almost completed so I am very excited to see the results.

-Kenny
