### ISSUE TITLE
The gene expression value was scaled,log-transformed? 

### ISSUE THREAD

**Issue by gancao** [jcao89757/TESSA#5]
The gene expression value was scaled,log-transformed? How to obtain the suitable expression value for TESSA from UMI count?

**Comment by jcao89757** [comment]
Hi @gancao，

Thanks for your question! Please find my preprocessing code attached.

```{r}
#Start from UMI raw counts.
 library(preprocessCore)
exp_data=log(exp_data+1)
exp_data[]=normalize.quantiles(exp_data)
#Use exp_data as the input of tessa.
```

You may also choose your own way to normalize the data. Please find some reference papers in the _Suggested pre-processing workflow_ section in the TESSA repo introduction (README.md). Thanks again for your interest in our tool!
Please let me know if you have any other questions.

Best regards, Ze
